IMAGE_OPEN_VOCABULARY_DETECTION_MODE = "open vocabulary detection"
IMAGE_CAPTION_GROUNDING_MODE = "caption + phrase grounding"

IMAGE_INFERENCE_MODES = [
    IMAGE_OPEN_VOCABULARY_DETECTION_MODE,
    IMAGE_CAPTION_GROUNDING_MODE,
]
